apiVersion: v1
kind: Service
metadata:
  name: service-demo1
spec:
  selector:
    app: spring-demo-kub
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: configmap-demo
data:
  application.properties:
    url=http://service-demo-provide/
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: spring-demo-kub
  labels:
    app: spring-demo-kub
spec:
  replicas: 1
  selector:
    matchLabels:
      app: spring-demo-kub
  template:
    metadata:
      labels:
        app: spring-demo-kub
    spec:
      containers:
        - name: spring-demo-kub
          image: localhost:32000/spring-demo-kub:latest
          ports:
            - containerPort: 8080
          volumeMounts:
            - name: configmap-demo
              mountPath: /workspace/config
      volumes:
        - name: configmap-demo
          configMap:
            name: configmap-demo
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: minimal-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /$2
spec:
  rules:
    - http:
        paths:
          - path: /service-demo1(/|$)(.*)
            pathType: Prefix
            backend:
              service:
                name: service-demo1
                port:
                  number: 80